# Model Defintion and Training

Now that we have parsed our training data, we can move on to defining our model. We will be using a number of different modules from pytorch:

- **torch.nn**
    - Provides the modules and classes we will use to define our network and its trainable layers
- **torch.nn.Functional**
    - Provides functional methods to compute functions that are stateless/not-trained (Activation functions, etc)
- **torch**
    - Used for creating and reshaping tensors throughout

To start, we need to load in the data we parsed during part 1. If you have not gone through part 1 yet, you should do so before running this notebook; alternatively, you can add some cells to load the data in a custom manner if you have it stored somewhere else.

In [1]:
# Again, this is a little bit of ipy magic
%store -r labels
%store -r images

Right now, the labels and images are stored as simple python lists. We'll use torch to convert them to tensors, which will allow us to easily apply more complex functions and transformations to the data.

In [7]:
import torch
training_labels = torch.tensor(labels)
training_images = torch.tensor(images)
print(type(training_images))

<class 'torch.Tensor'>


You can see above that we've converted our list into an object of class `torch.Tensor`. We'll need to keep our data as this type during the training and evaluation periods of our model. 

Although they may seem weird at first, you'll find a lot of familiarity with Tensor classes if you've worked with numpy before. In fact, you can even iterate through them like regular old lists:

In [40]:
tensor = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
for i, row in enumerate(tensor):
    print(f"Row {i}: {row}")

Row 0: tensor([1, 2, 3])
Row 1: tensor([4, 5, 6])
Row 2: tensor([7, 8, 9])


Similarily, if we wanted to iterate through the columns in our tensor:

In [44]:
for i, col in enumerate(tensor.T):
    print(f" Column {i}: {col}")

 Column 0: tensor([1, 4, 7])
 Column 1: tensor([2, 5, 8])
 Column 2: tensor([3, 6, 9])


I'm not going to go into too much more detail on tensor operations. Not only will you learn far more from the [documentation](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py), but I believe it's better to learn the power of tensors by seeing them in action.

The one last thing I'll show you is in-place operations on tensors. This differs a bit from numpy, so I'm calling it out now as we will be using it later on in this notebook:

In [68]:
tensor_less_1 = tensor.sub(1)  # Not in place. Returns a new tensor
print(f"Old Tensor:\n {tensor}")
print(f"New Tensor:\n {tensor_less_1}")

tensor_less_1 = tensor.sub_(1)  # In place. Modifies the tensor and returns a reference
print(f"Old Tensor:\n {tensor}")
print(f"New Tensor:\n {tensor_less_1}")

# Be careful capturing the output of in-place operations, as you must keep strict track of them to avoid unintentionally modifying data later on.

data = torch.tensor([[10.,11.,12.],[13.,14.,15.],[16.,17.,18.]])
normalized_data  = data.div_(data.sum())
normalized_data.add_(100)
print(data)


Old Tensor:
 tensor([[-19, -18, -17],
        [-16, -15, -14],
        [-13, -12, -11]])
New Tensor:
 tensor([[-20, -19, -18],
        [-17, -16, -15],
        [-14, -13, -12]])
Old Tensor:
 tensor([[-20, -19, -18],
        [-17, -16, -15],
        [-14, -13, -12]])
New Tensor:
 tensor([[-20, -19, -18],
        [-17, -16, -15],
        [-14, -13, -12]])
tensor([[100.0794, 100.0873, 100.0952],
        [100.1032, 100.1111, 100.1190],
        [100.1270, 100.1349, 100.1429]])
